// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjcjbfqmxlyslqjsczsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqY2piZnFteGx5c2xxanNjenN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDIzMzgsImV4cCI6MjA3NDAxODMzOH0.zS48PyqdsBKjJpbssTIdU6ZKGP5I20pkc06c_E71CCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});